[general]
library_name = "libPhreeqcRM"
output_file_path = "./phreeqcrm_library.jl"
module_name = "LibPhreeqcRM"
jll_pkg_name = "PhreeqcRM_jll"

prologue_file_path = "./prologue.jl"
epilogue_file_path = "./epilogue.jl"

auto_mutability = true              # Create mutable structures:
auto_mutability_with_new = true     # Allow creating empty structs
auto_mutability_ignorelist = []
auto_mutability_includelist = []

export_symbol_prefixes = ["CX", "clang_"]
